export interface DistrictLocation {
  name: string;
  wards: string[];
}

export interface CityLocation {
  city: string;
  districts: DistrictLocation[];
}

export const hcmcLocations: CityLocation[] = [
  {
    city: 'TP. Hồ Chí Minh',
    districts: [
      {
        name: 'Thành phố Thủ Đức',
        wards: [
          'An Khánh',
          'An Lợi Đông',
          'An Phú',
          'Bình Chiểu',
          'Bình Thọ',
          'Bình Trưng Đông',
          'Bình Trưng Tây',
          'Cát Lái',
          'Hiệp Bình Chánh',
          'Hiệp Bình Phước',
          'Hiệp Phú',
          'Linh Chiểu',
          'Linh Đông',
          'Linh Tây',
          'Linh Trung',
          'Linh Xuân',
          'Long Bình',
          'Long Phước',
          'Long Thạnh Mỹ',
          'Long Trường',
          'Phú Hữu',
          'Phước Bình',
          'Phước Long A',
          'Phước Long B',
          'Tăng Nhơn Phú A',
          'Tăng Nhơn Phú B',
          'Tam Bình',
          'Tam Phú',
          'Thạnh Mỹ Lợi',
          'Thảo Điền',
          'Thủ Thiêm',
          'Trường Thạnh',
          'Trường Thọ',
        ],
      },
      {
        name: 'Quận 1',
        wards: [
          'Phường Bến Nghé',
          'Phường Bến Thành',
          'Phường Cầu Kho',
          'Phường Cầu Ông Lãnh',
          'Phường Cô Giang',
          'Phường Đa Kao',
          'Phường Nguyễn Cư Trinh',
          'Phường Nguyễn Thái Bình',
          'Phường Phạm Ngũ Lão',
          'Phường Tân Định',
        ],
      },
      {
        name: 'Quận 3',
        wards: [
          'Phường 1',
          'Phường 2',
          'Phường 3',
          'Phường 4',
          'Phường 5',
          'Phường 6',
          'Phường 7',
          'Phường 8',
          'Phường 9',
          'Phường 10',
          'Phường 11',
          'Phường 12',
          'Phường 13',
          'Phường 14',
        ],
      },
      {
        name: 'Quận 4',
        wards: [
          'Phường 1',
          'Phường 2',
          'Phường 3',
          'Phường 4',
          'Phường 5',
          'Phường 6',
          'Phường 8',
          'Phường 9',
          'Phường 10',
          'Phường 12',
          'Phường 13',
          'Phường 14',
          'Phường 15',
          'Phường 16',
          'Phường 18',
        ],
      },
      {
        name: 'Quận 5',
        wards: [
          'Phường 1',
          'Phường 2',
          'Phường 3',
          'Phường 4',
          'Phường 5',
          'Phường 6',
          'Phường 7',
          'Phường 8',
          'Phường 9',
          'Phường 10',
          'Phường 11',
          'Phường 12',
          'Phường 13',
          'Phường 14',
          'Phường 15',
        ],
      },
      {
        name: 'Quận 6',
        wards: [
          'Phường 1',
          'Phường 2',
          'Phường 3',
          'Phường 4',
          'Phường 5',
          'Phường 6',
          'Phường 7',
          'Phường 8',
          'Phường 9',
          'Phường 10',
          'Phường 11',
          'Phường 12',
          'Phường 13',
          'Phường 14',
        ],
      },
      {
        name: 'Quận 7',
        wards: [
          'Phường Bình Thuận',
          'Phường Phú Mỹ',
          'Phường Phú Thuận',
          'Phường Tân Hưng',
          'Phường Tân Kiểng',
          'Phường Tân Phong',
          'Phường Tân Phú',
          'Phường Tân Quy',
          'Phường Tân Thuận Đông',
          'Phường Tân Thuận Tây',
        ],
      },
      {
        name: 'Quận 10',
        wards: [
          'Phường 1',
          'Phường 2',
          'Phường 3',
          'Phường 4',
          'Phường 5',
          'Phường 6',
          'Phường 7',
          'Phường 8',
          'Phường 9',
          'Phường 10',
          'Phường 11',
          'Phường 12',
          'Phường 13',
          'Phường 14',
          'Phường 15',
        ],
      },
      {
        name: 'Quận 11',
        wards: [
          'Phường 1',
          'Phường 2',
          'Phường 3',
          'Phường 4',
          'Phường 5',
          'Phường 6',
          'Phường 7',
          'Phường 8',
          'Phường 9',
          'Phường 10',
          'Phường 11',
          'Phường 12',
          'Phường 13',
          'Phường 14',
          'Phường 15',
          'Phường 16',
        ],
      },
      {
        name: 'Quận 12',
        wards: [
          'Phường An Phú Đông',
          'Phường Đông Hưng Thuận',
          'Phường Hiệp Thành',
          'Phường Tân Chánh Hiệp',
          'Phường Tân Hưng Thuận',
          'Phường Tân Thới Hiệp',
          'Phường Tân Thới Nhất',
          'Phường Thạnh Lộc',
          'Phường Thạnh Xuân',
          'Phường Thới An',
          'Phường Trung Mỹ Tây',
        ],
      },
      {
        name: 'Quận Bình Thạnh',
        wards: [
          'Phường 1',
          'Phường 2',
          'Phường 3',
          'Phường 5',
          'Phường 6',
          'Phường 7',
          'Phường 11',
          'Phường 12',
          'Phường 13',
          'Phường 14',
          'Phường 15',
          'Phường 17',
          'Phường 19',
          'Phường 21',
          'Phường 22',
          'Phường 24',
          'Phường 25',
          'Phường 26',
          'Phường 27',
          'Phường 28',
        ],
      },
      {
        name: 'Quận Bình Tân',
        wards: [
          'Phường An Lạc',
          'Phường An Lạc A',
          'Phường Bình Hưng Hòa',
          'Phường Bình Hưng Hòa A',
          'Phường Bình Hưng Hòa B',
          'Phường Bình Trị Đông',
          'Phường Bình Trị Đông A',
          'Phường Bình Trị Đông B',
          'Phường Tân Tạo',
          'Phường Tân Tạo A',
        ],
      },
      {
        name: 'Quận Gò Vấp',
        wards: [
          'Phường 1',
          'Phường 3',
          'Phường 4',
          'Phường 5',
          'Phường 6',
          'Phường 7',
          'Phường 8',
          'Phường 9',
          'Phường 10',
          'Phường 11',
          'Phường 12',
          'Phường 13',
          'Phường 14',
          'Phường 15',
          'Phường 16',
          'Phường 17',
        ],
      },
      {
        name: 'Quận Phú Nhuận',
        wards: [
          'Phường 1',
          'Phường 2',
          'Phường 3',
          'Phường 4',
          'Phường 5',
          'Phường 7',
          'Phường 8',
          'Phường 9',
          'Phường 10',
          'Phường 11',
          'Phường 13',
          'Phường 15',
          'Phường 17',
        ],
      },
      {
        name: 'Quận Tân Bình',
        wards: [
          'Phường 1',
          'Phường 2',
          'Phường 3',
          'Phường 4',
          'Phường 5',
          'Phường 6',
          'Phường 7',
          'Phường 8',
          'Phường 9',
          'Phường 10',
          'Phường 11',
          'Phường 12',
          'Phường 13',
          'Phường 14',
          'Phường 15',
        ],
      },
      {
        name: 'Quận Tân Phú',
        wards: [
          'Phường Hiệp Tân',
          'Phường Hòa Thạnh',
          'Phường Phú Thạnh',
          'Phường Phú Thọ Hòa',
          'Phường Phú Trung',
          'Phường Sơn Kỳ',
          'Phường Tân Quý',
          'Phường Tân Sơn Nhì',
          'Phường Tân Thành',
          'Phường Tân Thới Hòa',
          'Phường Tây Thạnh',
        ],
      },
      {
        name: 'Quận 8',
        wards: [
          'Phường 1',
          'Phường 2',
          'Phường 3',
          'Phường 4',
          'Phường 5',
          'Phường 6',
          'Phường 7',
          'Phường 8',
          'Phường 9',
          'Phường 10',
          'Phường 11',
          'Phường 12',
          'Phường 13',
          'Phường 14',
          'Phường 15',
          'Phường 16',
        ],
      },
      {
        name: 'Huyện Bình Chánh',
        wards: [
          'Thị trấn Tân Túc',
          'Xã An Phú Tây',
          'Xã Bình Chánh',
          'Xã Bình Hưng',
          'Xã Bình Lợi',
          'Xã Đa Phước',
          'Xã Hưng Long',
          'Xã Lê Minh Xuân',
          'Xã Phạm Văn Hai',
          'Xã Phong Phú',
          'Xã Quy Đức',
          'Xã Tân Kiên',
          'Xã Tân Nhựt',
          'Xã Tân Quý Tây',
          'Xã Vĩnh Lộc A',
          'Xã Vĩnh Lộc B',
        ],
      },
      {
        name: 'Huyện Cần Giờ',
        wards: [
          'Thị trấn Cần Thạnh',
          'Xã An Thới Đông',
          'Xã Bình Khánh',
          'Xã Long Hòa',
          'Xã Lý Nhơn',
          'Xã Tam Thôn Hiệp',
          'Xã Thạnh An',
        ],
      },
      {
        name: 'Huyện Củ Chi',
        wards: [
          'Thị trấn Củ Chi',
          'Xã An Nhơn Tây',
          'Xã An Phú',
          'Xã Bình Mỹ',
          'Xã Hòa Phú',
          'Xã Nhuận Đức',
          'Xã Phạm Văn Cội',
          'Xã Phú Hòa Đông',
          'Xã Phú Mỹ Hưng',
          'Xã Phước Hiệp',
          'Xã Phước Thạnh',
          'Xã Phước Vĩnh An',
          'Xã Tân An Hội',
          'Xã Tân Phú Trung',
          'Xã Tân Thạnh Đông',
          'Xã Tân Thạnh Tây',
          'Xã Tân Thông Hội',
          'Xã Thái Mỹ',
          'Xã Trung An',
          'Xã Trung Lập Hạ',
          'Xã Trung Lập Thượng',
        ],
      },
      {
        name: 'Huyện Hóc Môn',
        wards: [
          'Thị trấn Hóc Môn',
          'Xã Bà Điểm',
          'Xã Đông Thạnh',
          'Xã Nhị Bình',
          'Xã Tân Hiệp',
          'Xã Tân Thới Nhì',
          'Xã Tân Xuân',
          'Xã Thới Tam Thôn',
          'Xã Trung Chánh',
          'Xã Xuân Thới Đông',
          'Xã Xuân Thới Sơn',
          'Xã Xuân Thới Thượng',
        ],
      },
      {
        name: 'Huyện Nhà Bè',
        wards: [
          'Thị trấn Phú Xuân',
          'Xã Hiệp Phước',
          'Xã Long Thới',
          'Xã Nhơn Đức',
          'Xã Phước Kiển',
          'Xã Phước Lộc',
        ],
      },
    ],
  },
];
